name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-22.04
    # This grabs the WPILib docker container
    container: wpilib/roborio-cross-ubuntu:2025-22.04
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
    # Declares the repository safe and not under dubious ownership.
    - name: Add repository to git safe directories
      run: git config --global --add safe.directory $GITHUB_WORKSPACE
    # Fix for the distance sensor
    - name: Distance sensor fix
      run: mkdir temp
      # run: wget https://github.com/REVrobotics/2m-Distance-Sensor/releases/download/v2025.0.0/REV2mDistanceSensor-2025.0.0.zip
      # run: unzip REV2mDistanceSensor-2025.0.0.zip -d temp
      # run: cp -r temp/maven/com/revrobotics /root/wpilib/2025/maven/com
      # run: rm -rf temp
      # run: rm REV2mDistanceSensor-2025.0.0.zip
    # Grant execute permission for gradlew
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    # Runs a single command using the runners shell
    - name: Compile and run tests on robot code
      run: ./gradlew build
